apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-production
  labels:
    app: myapp
spec:
  replicas: 3  # Número deseado de réplicas en producción
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest  # Utiliza la última versión de la imagen de NGINX disponible en Docker Hub
        ports:
        - containerPort: 80  # Puerto en el que escucha tu aplicación
