name: Canary Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.AZURE_SP_APPID }} -p ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Set AKS Cluster Context
      run: az aks get-credentials --resource-group kuberetesServices --name myAKSKubernetes

    - name: Deploy to Canary
      run: |
        kubectl apply -f ./kubernetes/deployment.yaml
        echo "Canary deployment applied."

    - name: Check Canary Deployment
      run: |
        echo "Checking Canary deployment status..."
        kubectl get pods
        kubectl get services
        # Puedes agregar más comandos para obtener información adicional sobre el despliegue en Canary
