name: AKS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Cluster Context
      run: az aks get-credentials --resource-group <resource-group-name> --name <aks-cluster-name>

    - name: Deploy to AKS
      run: |
        # Aquí puedes agregar los comandos para desplegar tu aplicación en AKS usando kubectl
