name: prueba-docker
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.16
    steps:
      - name: Vision de la version
        run: |
          node -v
          cat /etc/os-release
