name: AKS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      run: |
        az login --service-principal -u ${{ secrets.AZURE_SP_APPID }} -p ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set AKS Cluster Context
      run: az aks get-credentials --resource-group kuberetesServices --name myAKSKubernetes

    - name: Deploy to AKS
      run: |
        # Aquí puedes agregar los comandos para desplegar tu aplicación en AKS usando kubectl
