name: Execution Upload Terraform

on:
  repository_dispatch:
  
jobs:
  execution:
    runs-on: ubuntu-latest
    steps:
      # Paso para configurar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: latest
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN_ID }} # Token de Terraform Cloud

      # Paso para inicializar Terraform
      - name: Terraform Init
        id: init
        run: terraform init

      # Paso para validar los archivos de configuración de Terraform
      - name: Terraform Validate
        id: validate
        run: terraform validate

      # Paso para planificar los cambios en Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true

      # Paso para verificar si el plan de Terraform ha fallado
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      # Paso para aplicar los cambios en Terraform (crear o actualizar recursos)
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Paso para obtener las salidas (outputs) de Terraform
      - name: Terraform Output
        run: terraform output